on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *" # Everday at midnight

jobs:
  remove-stale-branches:
    name: Remove Stale Branches
    runs-on: ubuntu-latest
    steps:
      - uses: fpicalausa/remove-stale-branches@v2.4.0
        with:
          exempt-protected-branches: true
          ignore-unknown-authors: true
          default-recipient: "helloWorlds0"
